# Generated by Django 4.0.7 on 2022-09-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
